"""empty message

Revision ID: 117d27f42cea
Revises: 7984c9bf432e
Create Date: 2026-05-07 16:26:42.994504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '117d27f42cea'
down_revision: Union[str, Sequence[str], None] = '7984c9bf432e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('voter_count', sa.Integer(), nullable=True))

    with op.batch_alter_table('answer_voter', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_answer_voter_question_id_question'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_answer_voter_question_id_answer'), 'answer', ['question_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer_voter', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_answer_voter_question_id_answer'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_answer_voter_question_id_question'), 'question', ['question_id'], ['id'])

    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.drop_column('voter_count')

    # ### end Alembic commands ###
