"""empty message

Revision ID: 175a51ceedf8
Revises: f7014f63b8a3
Create Date: 2026-05-14 10:29:19.875374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '175a51ceedf8'
down_revision: Union[str, Sequence[str], None] = 'f7014f63b8a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('del_yn', sa.String(length=1), server_default='N', nullable=False))
        batch_op.add_column(sa.Column('delete_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_column('delete_date')
        batch_op.drop_column('del_yn')

    # ### end Alembic commands ###
